### ISSUE TITLE
PRACTICA NESTOR CRUZ LEON

### ISSUE THREAD

**Issue by Nestor283** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Nestor283#1]
[PRACTICA-MATEMATICAS_DISCRETAS_NESTOR_CREUZ_LEON.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Nestor283/files/12571472/PRACTICA-MATEMATICAS_DISCRETAS_NESTOR_CREUZ_LEON.pdf)

**Comment by Anais-droid** [comment]
Portada 15
Objetivos 22
Figuras, ilustraciones y fotografías 15
Procedimiento 17
Resultados y conclusión 15
Calificación: 16.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
